# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout OpenEconomy
        uses: actions/checkout@v4
        with:
          path: OpenEconomy

      - name: checkout NATS-Fabric
        uses: actions/checkout@v4
        with:
          repository: xSaVageAU/NATS-Fabric
          path: nats-fabric-lib
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: build and publish NATS-Fabric
        run: |
          cd nats-fabric-lib
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal

      - name: build OpenEconomy
        run: |
          cd OpenEconomy
          chmod +x ./gradlew
          ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: OpenEconomy/build/libs/
